preset: laravel

disabled:
  - unused_use
  - phpdoc_no_package
  - phpdoc_var_without_name
  - single_class_element_per_statement
  - concat_without_spaces
  - logical_not_operators_with_spaces

finder:
  exclude:
    - "tests"
    - "resources"
