language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - hhvm
  - nightly

branches:
  only:
  - dev

script: phpunit --configuration phpunit.xml --coverage-text

cache:
  directories:
  - $HOME/.composer/cache